# Generated by Django 2.2.24 on 2021-06-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoty',
            new_name='ProductCategory',
        ),
    ]
